{
 "title": "Liberando Productos Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Requests - Server",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(server_requests_total{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Requests Number - Main Endpoint",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(main_requests_total{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Requests Number - Health Endpoint ",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(healthcheck_requests_total{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Requests Number - Agur Endpoint ",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(agur_requests_total{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Total Restarts - APP",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 7, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(kube_pod_container_status_restarts_total{container=\"fast-api-webapp\"}[1h]))"
    }
   ]
  }
 ]
}